In [70]:
df=pd.read_csv(r"C:\Users\rishi\Favorites\Downloads\mail_data.csv")

In [71]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.shape

(5572, 2)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [22]:
df['Message'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5567    False
5568    False
5569    False
5570    False
5571    False
Name: Message, Length: 5572, dtype: bool

In [ ]:
df.isnull().any()

Category    False
Message     False
dtype: bool

In [24]:
#replace the null values with a null string
df=df.where((pd.notnull(df)),'')

In [27]:
#label spam as 0; ham mail as 1;
df['Category']=df['Category'].map({'spam':0,'ham':1})

In [29]:
df.head()

   Category                                            Message
0         1  Go until jurong point, crazy.. Available only ...
1         1                      Ok lar... Joking wif u oni...
2         0  Free entry in 2 a wkly comp to win FA Cup fina...
3         1  U dun say so early hor... U c already then say...
4         1  Nah I don't think he goes to usf, he lives aro...

In [31]:
x=df['Message']
y=df['Category']

In [72]:
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [78]:
#splitting the data for training and testing
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2, random_state=3)
X_train.shape
Y_train.shape
X_test.shape
Y_test.shape

(1115,)

#feature extraction part

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [79]:
X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)
print(X_train_features.shape)
print(X_test_features.shape)

(4457, 7431)
(1115, 7431)

In [46]:
#converting y_train and y_test values as integer
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [49]:
X_train_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34775 stored elements and shape (4457, 7431)>

In [51]:

model = LogisticRegression()

In [58]:
model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)

In [81]:
# 1. Create model
model = LogisticRegression(max_iter=1000)

# 2. Train model
model.fit(X_train_features, Y_train)

# 3. Predict
prediction_on_training_data = model.predict(X_train_features)

# 4. Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_train, prediction_on_training_data)

print(accuracy)

0.9676912721561588

In [82]:
input_mail = ["I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times"]

# convert text to feature vectors
input_data_features = feature_extraction.transform(input_mail)

# making prediction

prediction = model.predict(input_data_features)
print(prediction)


if (prediction[0]==1):
  print('Ham mail')

else:
  print('Spam mail')

[1]
Ham mail